stages:
 - pytestfasta
 
 
 
fasta_test1:
 stage: pytestfasta
 
 before_script:
  - apt-get install -y python3-pip
  - pip3 install -U pytest
  
 script:
  - python3 -m pytest -v Testing/TestScrit/test_fasta_to_phylip.py


